accent = "#a1a1a1"
cursor = "#c0c0c0"
foreground = "#c0c0c0"
background = "#000000"
selection_foreground = "#e1e1e1"
selection_background = "#313131"

color0 = "#303030"
color1 = "#deeeed"
color2 = "#1bfd9c"
color3 = "#bababa"
color4 = "#a1a1a1"
color5 = "#66b2b2"
color6 = "#d1d1d1"
color7 = "#f1f1f1"
color8 = "#4d4d4d"
color9 = "#708090"
color10 = "#a6ffc9"
color11 = "#e1e1e1"
color12 = "#b1b1b1"
color13 = "#49c4c4"
color14 = "#d7d7d7"
color15 = "#ffffff"
